platform:ios, '7.0'
pod 'AFNetworking', '~> 2.0.2'
pod 'TBMacros', '~> 0.2'
pod 'MBProgressHUD', '~> 0.8'
pod 'TTTAttributedLabel', '~> 1.7.1'
pod 'KHFlatButton', '~> 1.0.0'
pod 'PHFRefreshControl', '~> 1.0.0'
pod 'MDCParallaxView', '~> 0.1.4'